name: Tests on push
on: [push]
jobs:
  run-unit-tests: 
    runs-on: ubuntu-latest
    steps:
      name: Checkout repo
      uses: actions/checkout@v2
      name: Setup JDK
      uses: actions/setup-java@v2
        with:
          java-version: 19
      name: Maven build
      uses: mvn package --no-transfer-progress
      name: Run tests
      uses: mvn test --no-transfer-progress