package dk.eamv.ferrari.scenes.employee;

import java.util.ArrayList;

// Made by: Mikkel
public class Employee {
    private int id;
    private String firstName;
    private String lastName;
    private String phoneNumber;
    private String email;
    private String password;
    private double maxLoan;
    private EmployeeStatus status;

    public Employee(int id, String firstName, String lastName, String phoneNumber, String email, String password, double maxLoan, EmployeeStatus status) {
        this.id = id;
        this.firstName = firstName;
        this.lastName = lastName;
        this.phoneNumber = phoneNumber;
        this.email = email;
        this.password = password;
        this.maxLoan = maxLoan;
        this.status = status;
    }
    
    // Overloaded to allow for CREATE operations. ID is removed since its autogenerated on INSERT.
    public Employee(String firstName, String lastName, String phoneNumber, String email, String password, double maxLoan) { 
        this(0, firstName, lastName, phoneNumber, email, password, maxLoan, EmployeeStatus.ACTIVE);
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public double getMaxLoan() {
        return maxLoan;
    }

    public void setMaxLoan(double maxLoan) {
        this.maxLoan = maxLoan;
    }

    public EmployeeStatus getStatus() {
        return status;
    }

    public void setStatus(EmployeeStatus status) {
        this.status = status;
    }

    public boolean isSalesManager() {
        return maxLoan == -1;
    }

    public ArrayList<String> getProperties() {
        ArrayList<String> properties = new ArrayList<String>();
        properties.add(password);
        properties.add(email);
        properties.add(String.valueOf(maxLoan));
        properties.add(phoneNumber);
        properties.add(lastName);
        properties.add(firstName);

        return properties;
    }

    @Override
    public String toString() {
        return String.format("%-4d %s %s", id, firstName, lastName);
    }
}
