package dk.eamv.ferrari.scenes.car;

import java.util.ArrayList;

// Made by: Mikkel
public class Car {
    private int id;
    private String model;
    private int year;
    private double price;

    public Car(int id, String model, int year, double price) {
        this.id = id;
        this.model = model;
        this.year = year;
        this.price = price;
    }

    // Overloaded to allow for CREATE operations. ID is removed since its autogenerated on INSERT.
    public Car(String model, int year, double price) {
        this.model = model;
        this.year = year;
        this.price = price;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getModel() {
        return model;
    }

    public void setModel(String model) {
        this.model = model;
    }

    public int getYear() {
        return year;
    }

    public void setYear(int year) {
        this.year = year;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public ArrayList<String> getPropperties() {
        ArrayList<String> propperties = new ArrayList<String>();
        propperties.add(String.valueOf(year));
        propperties.add(model);
        propperties.add(String.valueOf(price));

        return propperties;
    }

    @Override
    public String toString() {
        return String.format("%-15s %-5d %,.0f", model, year, price);
    }
}
