package dk.eamv.ferrari.scenes.customer;

import java.util.ArrayList;

public class Customer {

    private int id;
    private String firstName;
    private String lastName;
    private String phoneNumber;
    private String email;
    private String address;
    private String cpr;

    public Customer(int id, String firstName, String lastName, String phoneNumber, String email, String address,
            String cpr) {
        this.id = id;
        this.firstName = firstName;
        this.lastName = lastName;
        this.phoneNumber = phoneNumber;
        this.email = email;
        this.address = address;
        this.cpr = cpr;
    }
    
    //Overloaded to allow for CREATE operations. ID is removed since its autogenerated on INSERT.
    public Customer(String firstName, String lastName, String phoneNumber, String email, String address, String cpr) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.phoneNumber = phoneNumber;
        this.email = email;
        this.address = address;
        this.cpr = cpr;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getCpr() {
        return cpr;
    }

    public void setCpr(String cpr) {
        this.cpr = cpr;
    }

    public ArrayList<String> getPropperties() {
        ArrayList<String> propperties = new ArrayList<String>();
        propperties.add(address);
        propperties.add(email);
        propperties.add(cpr);
        propperties.add(phoneNumber);
        propperties.add(lastName);
        propperties.add(firstName);

        return propperties;
    }

    @Override
    public String toString() {
        return String.format("%-15s %s %s", cpr, firstName, lastName);
    }
}
